# Generated by Django 3.1 on 2020-10-03 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200929_2136'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=6000, verbose_name='نص التدوينة'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان التدوينة'),
        ),
    ]
